import { useState, useEffect, useRef } from 'react';
import { useSupabase } from '@/hooks/useSupabase';
import { useAuth } from '@/contexts/AuthContext';
import { Sparkles, RefreshCw, ChevronDown, ChevronUp } from 'lucide-react';

interface DailyBriefProps {
  autoGenerate?: boolean;
}

export default function DailyBrief({ autoGenerate }: DailyBriefProps = {}) {
  const supabase = useSupabase();
  const { user } = useAuth();
  const [brief, setBrief] = useState<string | null>(null);
  const [loading, setLoading] = useState(false);
  const [expanded, setExpanded] = useState(true);
  const [error, setError] = useState<string | null>(null);
  const autoGeneratedRef = useRef(false);

  const generate = async () => {
    if (!user) return;
    setLoading(true);
    setError(null);
    try {
      const { data, error: fnError } = await supabase.functions.invoke('daily-brief', {
        body: { user_id: user.id },
      });
      if (fnError) throw fnError;
      if (data?.error) throw new Error(data.error);
      setBrief(data.brief);
      setExpanded(true);
    } catch (e: any) {
      setError(e.message || 'Failed to generate brief');
    } finally {
      setLoading(false);
    }
  };

  // Auto-generate once per day when autoGenerate is true
  useEffect(() => {
    if (!autoGenerate || !user || autoGeneratedRef.current) return;
    const today = new Date().toISOString().split('T')[0];
    const lastGenDate = localStorage.getItem(`daily-brief-date-${user.id}`);
    if (lastGenDate === today) return;
    autoGeneratedRef.current = true;
    localStorage.setItem(`daily-brief-date-${user.id}`, today);
    generate();
  }, [autoGenerate, user]);

  return (
    <div className="data-card col-span-3 mb-4">
      <div className="flex items-center justify-between">
        <div className="flex items-center gap-2">
          <Sparkles size={14} className="text-primary" />
          <h3 className="text-sm font-medium">AI Daily Brief</h3>
        </div>
        <div className="flex items-center gap-1">
          {brief && (
            <button onClick={() => setExpanded(!expanded)} className="p-1 rounded hover:bg-muted">
              {expanded ? <ChevronUp size={14} className="text-muted-foreground" /> : <ChevronDown size={14} className="text-muted-foreground" />}
            </button>
          )}
          <button
            onClick={generate}
            disabled={loading}
            className="flex items-center gap-1 px-2 py-1 rounded-md bg-primary/10 text-primary text-xs hover:bg-primary/20 disabled:opacity-50"
          >
            {loading ? <RefreshCw size={12} className="animate-spin" /> : <Sparkles size={12} />}
            {brief ? 'Refresh' : 'Generate Brief'}
          </button>
        </div>
      </div>

      {error && (
        <p className="text-xs text-destructive mt-2">{error}</p>
      )}

      {brief && expanded && (
        <div className="mt-3 prose prose-sm prose-invert max-w-none text-sm leading-relaxed [&_h1]:text-base [&_h2]:text-sm [&_h3]:text-sm [&_p]:text-sm [&_li]:text-sm [&_strong]:text-foreground">
          <div dangerouslySetInnerHTML={{ __html: markdownToHtml(brief) }} />
        </div>
      )}

      {!brief && !loading && !error && (
        <p className="text-xs text-muted-foreground mt-2">Click "Generate Brief" to get your personalized daily priorities powered by AI.</p>
      )}
    </div>
  );
}

function markdownToHtml(md: string): string {
  return md
    .replace(/^### (.+)$/gm, '<h3>$1</h3>')
    .replace(/^## (.+)$/gm, '<h2>$1</h2>')
    .replace(/^# (.+)$/gm, '<h1>$1</h1>')
    .replace(/\*\*(.+?)\*\*/g, '<strong>$1</strong>')
    .replace(/\*(.+?)\*/g, '<em>$1</em>')
    .replace(/^- (.+)$/gm, '<li>$1</li>')
    .replace(/(<li>.*<\/li>\n?)+/g, '<ul>$&</ul>')
    .replace(/\n\n/g, '</p><p>')
    .replace(/\n/g, '<br/>')
    .replace(/^/, '<p>')
    .replace(/$/, '</p>');
}
